/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as libraries from "./libraries";
export { GainixBotPass__factory } from "./GainixBotPass__factory";
export { GainixMarketplace__factory } from "./GainixMarketplace__factory";
export { GainixNFT__factory } from "./GainixNFT__factory";
