/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGainixNFT,
  IGainixNFTInterface,
} from "../../../contracts/interfaces/IGainixNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGainixNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IGainixNFTInterface {
    return new Interface(_abi) as IGainixNFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IGainixNFT {
    return new Contract(address, _abi, runner) as unknown as IGainixNFT;
  }
}
