/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace GainixBotPass {
  export type SubscriptionStruct = {
    planId: BigNumberish;
    remainingCycles: BigNumberish;
    startedAt: BigNumberish;
    expiresAt: BigNumberish;
    totalPurchases: BigNumberish;
  };

  export type SubscriptionStructOutput = [
    planId: bigint,
    remainingCycles: bigint,
    startedAt: bigint,
    expiresAt: bigint,
    totalPurchases: bigint
  ] & {
    planId: bigint;
    remainingCycles: bigint;
    startedAt: bigint;
    expiresAt: bigint;
    totalPurchases: bigint;
  };
}

export interface GainixBotPassInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "configurePlan"
      | "consumeCycles"
      | "getSubscription"
      | "operators"
      | "owner"
      | "pause"
      | "paused"
      | "pendingOwner"
      | "plans"
      | "renewSubscription"
      | "renounceOwnership"
      | "setOperator"
      | "setSubscriptionPeriod"
      | "setTreasury"
      | "subscribe"
      | "subscriptionOf"
      | "subscriptionPeriod"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BotPassPurchased"
      | "CycleConsumed"
      | "OperatorUpdated"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "PlanConfigured"
      | "SubscriptionPeriodUpdated"
      | "SubscriptionUpdated"
      | "TreasuryUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configurePlan",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "consumeCycles",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "plans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "renewSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSubscriptionPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configurePlan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consumeCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "plans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renewSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSubscriptionPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace BotPassPurchasedEvent {
  export type InputTuple = [
    user: AddressLike,
    planId: BigNumberish,
    amountPaid: BigNumberish,
    cyclesAdded: BigNumberish,
    renewal: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    planId: bigint,
    amountPaid: bigint,
    cyclesAdded: bigint,
    renewal: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    planId: bigint;
    amountPaid: bigint;
    cyclesAdded: bigint;
    renewal: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CycleConsumedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    remainingCycles: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    remainingCycles: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    remainingCycles: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorUpdatedEvent {
  export type InputTuple = [operator: AddressLike, isOperator: boolean];
  export type OutputTuple = [operator: string, isOperator: boolean];
  export interface OutputObject {
    operator: string;
    isOperator: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanConfiguredEvent {
  export type InputTuple = [
    planId: BigNumberish,
    priceWei: BigNumberish,
    cycles: BigNumberish,
    active: boolean
  ];
  export type OutputTuple = [
    planId: bigint,
    priceWei: bigint,
    cycles: bigint,
    active: boolean
  ];
  export interface OutputObject {
    planId: bigint;
    priceWei: bigint;
    cycles: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionPeriodUpdatedEvent {
  export type InputTuple = [oldPeriod: BigNumberish, newPeriod: BigNumberish];
  export type OutputTuple = [oldPeriod: bigint, newPeriod: bigint];
  export interface OutputObject {
    oldPeriod: bigint;
    newPeriod: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    planId: BigNumberish,
    remainingCycles: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    planId: bigint,
    remainingCycles: bigint
  ];
  export interface OutputObject {
    user: string;
    planId: bigint;
    remainingCycles: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [
    previousTreasury: AddressLike,
    newTreasury: AddressLike
  ];
  export type OutputTuple = [previousTreasury: string, newTreasury: string];
  export interface OutputObject {
    previousTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GainixBotPass extends BaseContract {
  connect(runner?: ContractRunner | null): GainixBotPass;
  waitForDeployment(): Promise<this>;

  interface: GainixBotPassInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  configurePlan: TypedContractMethod<
    [
      planId: BigNumberish,
      priceWei: BigNumberish,
      cycles: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;

  consumeCycles: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getSubscription: TypedContractMethod<
    [user: AddressLike],
    [GainixBotPass.SubscriptionStructOutput],
    "view"
  >;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  plans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        priceWei: bigint;
        cycles: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  renewSubscription: TypedContractMethod<
    [planId: BigNumberish],
    [void],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setOperator: TypedContractMethod<
    [operator: AddressLike, isOperator: boolean],
    [void],
    "nonpayable"
  >;

  setSubscriptionPeriod: TypedContractMethod<
    [newPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  subscribe: TypedContractMethod<[planId: BigNumberish], [void], "payable">;

  subscriptionOf: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, boolean] & {
        planId: bigint;
        remainingCycles: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  subscriptionPeriod: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "configurePlan"
  ): TypedContractMethod<
    [
      planId: BigNumberish,
      priceWei: BigNumberish,
      cycles: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "consumeCycles"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getSubscription"
  ): TypedContractMethod<
    [user: AddressLike],
    [GainixBotPass.SubscriptionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "plans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        priceWei: bigint;
        cycles: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renewSubscription"
  ): TypedContractMethod<[planId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [operator: AddressLike, isOperator: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSubscriptionPeriod"
  ): TypedContractMethod<[newPeriod: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<[planId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "subscriptionOf"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, boolean] & {
        planId: bigint;
        remainingCycles: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "subscriptionPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BotPassPurchased"
  ): TypedContractEvent<
    BotPassPurchasedEvent.InputTuple,
    BotPassPurchasedEvent.OutputTuple,
    BotPassPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "CycleConsumed"
  ): TypedContractEvent<
    CycleConsumedEvent.InputTuple,
    CycleConsumedEvent.OutputTuple,
    CycleConsumedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorUpdated"
  ): TypedContractEvent<
    OperatorUpdatedEvent.InputTuple,
    OperatorUpdatedEvent.OutputTuple,
    OperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlanConfigured"
  ): TypedContractEvent<
    PlanConfiguredEvent.InputTuple,
    PlanConfiguredEvent.OutputTuple,
    PlanConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionPeriodUpdated"
  ): TypedContractEvent<
    SubscriptionPeriodUpdatedEvent.InputTuple,
    SubscriptionPeriodUpdatedEvent.OutputTuple,
    SubscriptionPeriodUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionUpdated"
  ): TypedContractEvent<
    SubscriptionUpdatedEvent.InputTuple,
    SubscriptionUpdatedEvent.OutputTuple,
    SubscriptionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BotPassPurchased(address,uint256,uint256,uint256,bool,uint256)": TypedContractEvent<
      BotPassPurchasedEvent.InputTuple,
      BotPassPurchasedEvent.OutputTuple,
      BotPassPurchasedEvent.OutputObject
    >;
    BotPassPurchased: TypedContractEvent<
      BotPassPurchasedEvent.InputTuple,
      BotPassPurchasedEvent.OutputTuple,
      BotPassPurchasedEvent.OutputObject
    >;

    "CycleConsumed(address,uint256,uint256)": TypedContractEvent<
      CycleConsumedEvent.InputTuple,
      CycleConsumedEvent.OutputTuple,
      CycleConsumedEvent.OutputObject
    >;
    CycleConsumed: TypedContractEvent<
      CycleConsumedEvent.InputTuple,
      CycleConsumedEvent.OutputTuple,
      CycleConsumedEvent.OutputObject
    >;

    "OperatorUpdated(address,bool)": TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;
    OperatorUpdated: TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlanConfigured(uint256,uint256,uint256,bool)": TypedContractEvent<
      PlanConfiguredEvent.InputTuple,
      PlanConfiguredEvent.OutputTuple,
      PlanConfiguredEvent.OutputObject
    >;
    PlanConfigured: TypedContractEvent<
      PlanConfiguredEvent.InputTuple,
      PlanConfiguredEvent.OutputTuple,
      PlanConfiguredEvent.OutputObject
    >;

    "SubscriptionPeriodUpdated(uint64,uint64)": TypedContractEvent<
      SubscriptionPeriodUpdatedEvent.InputTuple,
      SubscriptionPeriodUpdatedEvent.OutputTuple,
      SubscriptionPeriodUpdatedEvent.OutputObject
    >;
    SubscriptionPeriodUpdated: TypedContractEvent<
      SubscriptionPeriodUpdatedEvent.InputTuple,
      SubscriptionPeriodUpdatedEvent.OutputTuple,
      SubscriptionPeriodUpdatedEvent.OutputObject
    >;

    "SubscriptionUpdated(address,uint256,uint256)": TypedContractEvent<
      SubscriptionUpdatedEvent.InputTuple,
      SubscriptionUpdatedEvent.OutputTuple,
      SubscriptionUpdatedEvent.OutputObject
    >;
    SubscriptionUpdated: TypedContractEvent<
      SubscriptionUpdatedEvent.InputTuple,
      SubscriptionUpdatedEvent.OutputTuple,
      SubscriptionUpdatedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
