/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libraries from "./libraries";
export type { libraries };
export type { GainixBotPass } from "./GainixBotPass";
export type { GainixMarketplace } from "./GainixMarketplace";
export type { GainixNFT } from "./GainixNFT";
export type { GainixWithdrawalVault } from "./GainixWithdrawalVault";
