ALTER TYPE "WalletLedgerType" ADD VALUE IF NOT EXISTS 'GXN_TOKEN_REWARD';
ALTER TYPE "WalletLedgerType" ADD VALUE IF NOT EXISTS 'GXN_TOKEN_DEDUCTION';

ALTER TABLE "wallets" ADD COLUMN IF NOT EXISTS "gxnTokenBalance" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "withdrawals" ADD COLUMN IF NOT EXISTS "gxnDeductionAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "withdrawals" ADD COLUMN IF NOT EXISTS "gxnTokens" DOUBLE PRECISION NOT NULL DEFAULT 0;
