ALTER TABLE "nfts" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "nfts" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'General';
ALTER TABLE "nfts" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "nfts" ADD COLUMN IF NOT EXISTS "basePrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "nfts" ALTER COLUMN "imageUrl" DROP DEFAULT;
ALTER TABLE "nfts" ALTER COLUMN "basePrice" DROP DEFAULT;
